
export const shop = [
    {
        pid:0,
        type:"Shirts",
        washingTypes:[0,0,0,0],
        washingTypesPrices:[5,10,15,20],
        individualPriceSummation:0,
        totalPrice:0,
        totalQuantity:0,
        image:"/images/shirt.jpeg"
    },
    {
        pid:1,
        type:"T-shirts",
        washingTypes:[0,0,0,0],
        washingTypesPrices:[5,10,15,20],
        individualPriceSummation:0,
        totalPrice:0,
        totalQuantity:0,
        image:"/images/t-shirt.jpeg"
    },
    {
        pid:2,
        type:"Trousers",
        washingTypes:[0,0,0,0],
        washingTypesPrices:[5,10,15,20],
        individualPriceSummation:0,
        totalPrice:0,
        totalQuantity:0,
        image:"/images/trousers.jpg"
    },
    {
        pid:3,
        type:"Jeans",
        washingTypes:[0,0,0,0],
        washingTypesPrices:[5,10,15,20],
        individualPriceSummation:0,
        totalPrice:0,
        totalQuantity:0,
        image:"/images/jeans.jpg"
    },
    {
        pid:4,
        type:"Joggers",
        washingTypes:[0,0,0,0],
        washingTypesPrices:[5,10,15,20],
        individualPriceSummation:0,
        totalPrice:0,
        totalQuantity:0,
        image:"/images/joggers.jpg"
    }
]
